### ISSUE TITLE
Status of the library

### ISSUE THREAD

**Issue by avstudios** [thosakwe/dart_phaser#1]
Hi,
What is the status of this library? 
Can it be used in production?

**Comment by thosakwe** [comment]
Yes. There's an example: https://github.com/thosakwe/dart_phaser_example

**Comment by thosakwe** [comment]
Keep in mind, you have to use "allowInterop(...)" in a lot of places, because of the structure of Phaser. Each function also must take a Game instance as a parameter.

Adding game states will also be cumbersome. In fact, I'm not sure they even work; haven't tried.

Anyways, this is just a Dart binding, and TypeScript works way better with Phaser.

**Comment by thosakwe** [comment]
https://github.com/thosakwe/phaser-ts-boilerplate might help

**Comment by avstudios** [comment]
Great, the example works for me. I will try to play more with it now. I hope I won't need to use TypeScript ;)
